python pacman.py -l maze_10_bottomright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_10_topleft.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_10_topright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_20_bottomright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_20_topleft.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_20_topright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_30_bottomright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_30_topleft.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_30_topright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_40_bottomright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_40_topleft.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_40_topright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_50_bottomright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_50_topleft.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_50_topright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_60_bottomright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_60_topleft.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_60_topright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_70_bottomright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_70_topleft.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_70_topright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_80_bottomright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_80_topleft.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_80_topright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_90_bottomright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_90_topleft.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_90_topright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_100_bottomright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_100_topleft.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_100_topright.lay -z .25 -p SearchAgent -a fn=dstaropt,heuristic=manhattanHeuristic -q
python pacman.py -l maze_10_bottomright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_10_topleft.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_10_topright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_20_bottomright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_20_topleft.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_20_topright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_30_bottomright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_30_topleft.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_30_topright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_40_bottomright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_40_topleft.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_40_topright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_50_bottomright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_50_topleft.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_50_topright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_60_bottomright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_60_topleft.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_60_topright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_70_bottomright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_70_topleft.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_70_topright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_80_bottomright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_80_topleft.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_80_topright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_90_bottomright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_90_topleft.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_90_topright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_100_bottomright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_100_topleft.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q
python pacman.py -l maze_100_topright.lay -z .25 -p SearchAgent -a fn=dstar,heuristic=manhattanHeuristic -q